[package]
name = "glnis_gammaboard_api"
version = "0.1.0"
edition = "2024"

[lib]
name = "_rust"
path = "src/rust/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
gammalooprs = { git = "https://github.com/alphal00p/gammaloop.git", rev = "49d3cc84aa2c5d81506b2a5e82cc5bfeafab0e01", package = "gammalooprs" }
gammaloop_api = { git = "https://github.com/alphal00p/gammaloop.git", rev = "49d3cc84aa2c5d81506b2a5e82cc5bfeafab0e01", package = "gammaloop-api", default-features = false, features = ["cli", "no_pyo3"] }
pyo3 = { version = "0.28", features = ["extension-module"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"


[patch.crates-io]
graphica = { git = "https://github.com/alphal00p/symbolica", rev = "4d0a833eb8e059d1f95bdae5abed2559830b235f" }
numerica = { git = "https://github.com/alphal00p/symbolica", rev = "4d0a833eb8e059d1f95bdae5abed2559830b235f" }
symbolica = { git = "https://github.com/alphal00p/symbolica", rev = "4d0a833eb8e059d1f95bdae5abed2559830b235f" }
