[package]
name = "glnis_gammaboard_api"
version = "0.1.0"
edition = "2024"

[lib]
name = "_rust"
path = "src/rust/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
gammalooprs = { git = "https://github.com/alphal00p/gammaloop.git", branch = "ir_safe_threshold_subtraction", package = "gammalooprs" }
gammaloop_api = { git = "https://github.com/alphal00p/gammaloop.git", branch = "ir_safe_threshold_subtraction", package = "gammaloop-api", default-features = false, features = ["cli", "no_pyo3"] }
pyo3 = { version = "0.28", features = ["extension-module"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[patch."https://github.com/alphal00p/gammaloop.git"]
gammaloop-workspace-hack = { path = "vendor/gammaloop-workspace-hack" }

[patch.crates-io]
graphica = { path = "vendor/symbolica/lib/graphica" }
numerica = { git = "https://github.com/symbolica-dev/symbolica", branch = "dev" }
symbolica = { path = "vendor/symbolica" }
